---
# Global configuration definitions

## Initialize via configuration file, omits use of grr_config_updater intialize

Server.initialized: true

## Include file with certificate and key definitions

Config.includes:
    - '/etc/grr/server.local.yaml'

## Database

Mysql.host: '%(MYSQL_HOST|env)'
Mysql.port: '%(MYSQL_PORT|env)'
Mysql.database: '%(MYSQL_DATABASE|env)'
Mysql.username: '%(MYSQL_USERNAME|env)'
Mysql.password: '%(MYSQL_PASSWORD|env)'
Database.implementation: MysqlDB

## Monitoring

Monitoring.alert_email: '%(MONITORING_ALERT_EMAIL|env)'
Monitoring.emergency_access_email: '%(MONITORING_EMERGENCY_EMAIL|env)'

## Logging

Installer.logfile: '%(Logging.path)/client_installer.txt'
Logging.domain: '%(EXTERNAL_HOSTNAME|env)'

# Context specific configurations

## AdminUI Context

AdminUI Context:
    AdminUI.csrf_secret_key: '%(CSRF_SECRET_KEY|env)'
    AdminUI.url: 'http://%(EXTERNAL_HOSTNAME|env):%(ADMINUI_PORT|env)'
    AdminUI.webauth_manager: '%(ADMINUI_WEBAUTH_MANAGER|env)'
    AdminUI.heading: '%(ADMINUI_HEADING|env)'
    AdminUI.remote_user_trusted_ips:
        - '%(REMOTE_TRUSTED_IPV4|env)'
        - '%(REMOTE_TRUSTED_IPV6|env)'
    Monitoring.http_port: '%(MONITORING_HTTP_PORT|env)'
    Logging.path: /var/log/grr/admin

## Client Context

Client Context:
    Client.foreman_check_frequency: '%(FOREMAN_CHECK_FREQUENCY|env)'
    Client.poll_max: '%(POLL_MAX|env)'
    Client.proxy_servers:
        - '%(CLIENT_PROXY_SERVER|env)'
    Client.server_urls:
        - 'http://%(FRONTEND_BIND_ADDRESS|env):%(FRONTEND_BIND_PORT|env)/'

## Frontend Context

HTTPServer Context:
    Monitoring.http_port: '%(MONITORING_HTTP_PORT|env)'
    Logging.path: /var/log/grr/frontend

Worker Context:
    Monitoring.http_port: '%(MONITORING_HTTP_PORT|env)'
    Logging.path: /var/log/grr/worker

## Target specific Contexts

Target:Darwin:
    Osquery.path: '%(OSQUERY_PATH_DARWIN|env)'
    Config.includes:
        - 'build.yaml'
    Logging.path: /var/log/grr

Target:Linux:
    Osquery.path: '%(OSQUERY_PATH_LINUX|env)'
    Config.includes:
        - 'build.yaml'
    Logging.path: /var/log/grr

Target:Windows:
    Osquery.path: '%(PROGRAMFILES|env)\\osquery\\osqueryi.exe'
    Config.includes:
        - 'build.yaml'
    Logging.path: 'C:\Windows\Temp\grr'
