---
# Use this config file for initialization

Server.initialized: True

# Database

Datastore.implementation: MySQLAdvancedDataStore
Mysql.host: "%(MYSQL_HOST|env)"
Mysql.port: "%(MYSQL_PORT|env)"
Mysql.database_name: "%(MYSQL_DATABASE_NAME|env)"
Mysql.database_username: "%(MYSQL_DATABASE_USERNAME|env)"
Mysql.database_password: "%(MYSQL_DATABASE_PASSWORD|env)"
Mysql.database: "%(MYSQL_DATABASE|env)"
Mysql.username: "%(MYSQL_DATABASE_USERNAME|env)"
Mysql.password: "%(MYSQL_DATABASE_PASSWORD|env)"

# Use of AFF4 datastore is discouraged
# https://github.com/google/grr-doc/blob/master/installing-grr-server/overview.md#datastore

Database.aff4_enabled: false
Database.implementation: MysqlDB
Blobstore.implementation: DbBlobStore
Database.enabled: True

# Monitoring

Monitoring.alert_email: "%(MONITORING_ALERT_EMAIL|env)"
Monitoring.emergency_access_email: "%(MONITORING_EMERGENCY_EMAIL|env)"
Monitoring.http_port: "%(MONITORING_HTTP_PORT|env)"

# Certificate and key management

Frontend.bind_port: "%(FRONTEND_SERVER_PORT|env)"
Server.rsa_key_length: "%(SERVER_RSA_KEY_LENGTH|env)"
PrivateKeys.server_key: "%(%(FRONTEND_PRIVATE_KEY_PATH|env)|file)"
Frontend.certificate: "%(%(FRONTEND_CERT_PATH|env)|file)"
PrivateKeys.executable_signing_private_key: "%(%(FRONTEND_PRIVATE_SIGNING_KEY_PATH|env)|file)"
PrivateKeys.ca_key: "%(%(CA_PRIVATE_KEY_PATH|env)|file)"
CA.certificate: "%(%(CA_CERT_PATH|env)|file)"
Client.executable_signing_public_key: "%(%(FRONTEND_PUBLIC_SIGNING_KEY_PATH|env)|file)"

# Logging

Logging.path: /var/log/grr/
# Use verbose logging only for debugging purposes
# Logging.verbose: True
Logging.verbose: False
Logging.domain: "%(EXTERNAL_HOSTNAME|env)"

# Target specific configuration

Target:Darwin:
  Osquery.path: "%(OSQUERY_PATH_DARWIN|env)"
  Config.includes:
    - build.yaml

Target:Linux:
  Osquery.path: "%(OSQUERY_PATH_LINUX|env)"
  Config.includes:
    - build.yaml

Target:Windows:
  Osquery.path: "%(PROGRAMFILES|env)\\osquery\\osqueryi.exe"
  Config.includes:
    - build.yaml

# Client Context

Client.executable_signing_public_key: "%(%(FRONTEND_PUBLIC_SIGNING_KEY_PATH|env)|file)"
Client.server_urls:
  - "http://%(FRONTEND_BIND_ADDRESS|env):%(FRONTEND_BIND_PORT|env)/"

Client Context:
  PrivateKeys.ca_key: "%(%(CA_PRIVATE_KEY_PATH|env)|file)"
  CA.certificate: "%(%(CA_CERT_PATH|env)|file)"
  Client.foreman_check_frequency: "%(FOREMAN_CHECK_FREQUENCY|env)"
  Client.poll_max: "%(POLL_MAX|env)"
  Client.proxy_servers:
    - "%(CLIENT_PROXY_SERVER|env)"

# AdminUI Context

AdminUI Context:
  AdminUI.csrf_secret_key: "%(CSRF_SECRET_KEY|env)"
  AdminUI.url: "http://%(EXTERNAL_HOSTNAME|env):%(ADMINUI_PORT|env)"
  AdminUI.port: "%(ADMINUI_PORT|env)"
  AdminUI.webauth_manager: "%(ADMINUI_WEBAUTH_MANAGER|env)"
  AdminUI.remote_user_trusted_ips:
    - "%(REMOTE_TRUSTED_IPV4|env)"
    - "%(REMOTE_TRUSTED_IPV6|env)"
